### ISSUE TITLE
expects "vue-template-compiler" with vue 3

### ISSUE THREAD

**Issue by benjaminlewandowski** [antfu/vite-plugin-icons#18]
after update to 0.3.0 the plugin throws an errow when using vue 3.

> Error: Cannot find module 'vue-template-compiler'

rollback to 0.2.4 fixed it for me.
